const fashionJewellery = [
  {
    id: 1,
    title: "Essence Mascara Lash Princess",
    description:
      "The Essence Mascara Lash Princess is a popular mascara known for its volumizing and lengthening effects. Achieve dramatic lashes with this long-lasting and cruelty-free formula.",
    category: "beauty",
    price: 9.99,
    discountPercentage: 10.48,
    rating: 2.56,
    stock: 99,
    tags: ["beauty", "mascara"],
    brand: "Essence",
    sku: "BEA-ESS-ESS-001",
    weight: 4,
    dimensions: {
      width: 15.14,
      height: 13.08,
      depth: 22.99,
    },
    warrantyInformation: "1 week warranty",
    shippingInformation: "Ships in 3-5 business days",
    availabilityStatus: "In Stock",
    reviews: [
      {
        rating: 3,
        comment: "Would not recommend!",
        date: "2025-04-30T09:41:02.053Z",
        reviewerName: "Eleanor Collins",
        reviewerEmail: "eleanor.collins@x.dummyjson.com",
      },
      {
        rating: 4,
        comment: "Very satisfied!",
        date: "2025-04-30T09:41:02.053Z",
        reviewerName: "Lucas Gordon",
        reviewerEmail: "lucas.gordon@x.dummyjson.com",
      },
      {
        rating: 5,
        comment: "Highly impressed!",
        date: "2025-04-30T09:41:02.053Z",
        reviewerName: "Eleanor Collins",
        reviewerEmail: "eleanor.collins@x.dummyjson.com",
      },
    ],
    returnPolicy: "No return policy",
    minimumOrderQuantity: 48,
    meta: {
      createdAt: "2025-04-30T09:41:02.053Z",
      updatedAt: "2025-04-30T09:41:02.053Z",
      barcode: "5784719087687",
      qrCode: "https://cdn.dummyjson.com/public/qr-code.png",
    },
    images: [
      "https://cdn.dummyjson.com/product-images/beauty/essence-mascara-lash-princess/1.webp",
    ],
    thumbnail:
      "https://cdn.dummyjson.com/product-images/beauty/essence-mascara-lash-princess/thumbnail.webp",
  },
  {
    id: 2,
    title: "Eyeshadow Palette with Mirror",
    description:
      "The Eyeshadow Palette with Mirror offers a versatile range of eyeshadow shades for creating stunning eye looks. With a built-in mirror, it's convenient for on-the-go makeup application.",
    category: "beauty",
    price: 19.99,
    discountPercentage: 18.19,
    rating: 2.86,
    stock: 34,
    tags: ["beauty", "eyeshadow"],
    brand: "Glamour Beauty",
    sku: "BEA-GLA-EYE-002",
    weight: 9,
    dimensions: {
      width: 9.26,
      height: 22.47,
      depth: 27.67,
    },
    warrantyInformation: "1 year warranty",
    shippingInformation: "Ships in 2 weeks",
    availabilityStatus: "In Stock",
    reviews: [
      {
        rating: 5,
        comment: "Great product!",
        date: "2025-04-30T09:41:02.053Z",
        reviewerName: "Savannah Gomez",
        reviewerEmail: "savannah.gomez@x.dummyjson.com",
      },
      {
        rating: 4,
        comment: "Awesome product!",
        date: "2025-04-30T09:41:02.053Z",
        reviewerName: "Christian Perez",
        reviewerEmail: "christian.perez@x.dummyjson.com",
      },
      {
        rating: 1,
        comment: "Poor quality!",
        date: "2025-04-30T09:41:02.053Z",
        reviewerName: "Nicholas Bailey",
        reviewerEmail: "nicholas.bailey@x.dummyjson.com",
      },
    ],
    returnPolicy: "7 days return policy",
    minimumOrderQuantity: 20,
    meta: {
      createdAt: "2025-04-30T09:41:02.053Z",
      updatedAt: "2025-04-30T09:41:02.053Z",
      barcode: "9170275171413",
      qrCode: "https://cdn.dummyjson.com/public/qr-code.png",
    },
    images: [
      "https://cdn.dummyjson.com/product-images/beauty/eyeshadow-palette-with-mirror/1.webp",
    ],
    thumbnail:
      "https://cdn.dummyjson.com/product-images/beauty/eyeshadow-palette-with-mirror/thumbnail.webp",
  },
  {
    id: 3,
    title: "Powder Canister",
    description:
      "The Powder Canister is a finely milled setting powder designed to set makeup and control shine. With a lightweight and translucent formula, it provides a smooth and matte finish.",
    category: "beauty",
    price: 14.99,
    discountPercentage: 9.84,
    rating: 4.64,
    stock: 89,
    tags: ["beauty", "face powder"],
    brand: "Velvet Touch",
    sku: "BEA-VEL-POW-003",
    weight: 8,
    dimensions: {
      width: 29.27,
      height: 27.93,
      depth: 20.59,
    },
    warrantyInformation: "3 months warranty",
    shippingInformation: "Ships in 1-2 business days",
    availabilityStatus: "In Stock",
    reviews: [
      {
        rating: 4,
        comment: "Would buy again!",
        date: "2025-04-30T09:41:02.053Z",
        reviewerName: "Alexander Jones",
        reviewerEmail: "alexander.jones@x.dummyjson.com",
      },
      {
        rating: 5,
        comment: "Highly impressed!",
        date: "2025-04-30T09:41:02.053Z",
        reviewerName: "Elijah Cruz",
        reviewerEmail: "elijah.cruz@x.dummyjson.com",
      },
      {
        rating: 1,
        comment: "Very dissatisfied!",
        date: "2025-04-30T09:41:02.053Z",
        reviewerName: "Avery Perez",
        reviewerEmail: "avery.perez@x.dummyjson.com",
      },
    ],
    returnPolicy: "No return policy",
    minimumOrderQuantity: 22,
    meta: {
      createdAt: "2025-04-30T09:41:02.053Z",
      updatedAt: "2025-04-30T09:41:02.053Z",
      barcode: "8418883906837",
      qrCode: "https://cdn.dummyjson.com/public/qr-code.png",
    },
    images: [
      "https://cdn.dummyjson.com/product-images/beauty/powder-canister/1.webp",
    ],
    thumbnail:
      "https://cdn.dummyjson.com/product-images/beauty/powder-canister/thumbnail.webp",
  },
  {
    id: 4,
    title: "Red Lipstick",
    description:
      "The Red Lipstick is a classic and bold choice for adding a pop of color to your lips. With a creamy and pigmented formula, it provides a vibrant and long-lasting finish.",
    category: "beauty",
    price: 12.99,
    discountPercentage: 12.16,
    rating: 4.36,
    stock: 91,
    tags: ["beauty", "lipstick"],
    brand: "Chic Cosmetics",
    sku: "BEA-CHI-LIP-004",
    weight: 1,
    dimensions: {
      width: 18.11,
      height: 28.38,
      depth: 22.17,
    },
    warrantyInformation: "3 year warranty",
    shippingInformation: "Ships in 1 week",
    availabilityStatus: "In Stock",
    reviews: [
      {
        rating: 4,
        comment: "Great product!",
        date: "2025-04-30T09:41:02.053Z",
        reviewerName: "Liam Garcia",
        reviewerEmail: "liam.garcia@x.dummyjson.com",
      },
      {
        rating: 5,
        comment: "Great product!",
        date: "2025-04-30T09:41:02.053Z",
        reviewerName: "Ruby Andrews",
        reviewerEmail: "ruby.andrews@x.dummyjson.com",
      },
      {
        rating: 5,
        comment: "Would buy again!",
        date: "2025-04-30T09:41:02.053Z",
        reviewerName: "Clara Berry",
        reviewerEmail: "clara.berry@x.dummyjson.com",
      },
    ],
    returnPolicy: "7 days return policy",
    minimumOrderQuantity: 40,
    meta: {
      createdAt: "2025-04-30T09:41:02.053Z",
      updatedAt: "2025-04-30T09:41:02.053Z",
      barcode: "9467746727219",
      qrCode: "https://cdn.dummyjson.com/public/qr-code.png",
    },
    images: [
      "https://cdn.dummyjson.com/product-images/beauty/red-lipstick/1.webp",
    ],
    thumbnail:
      "https://cdn.dummyjson.com/product-images/beauty/red-lipstick/thumbnail.webp",
  },
  {
    id: 5,
    title: "Red Nail Polish",
    description:
      "The Red Nail Polish offers a rich and glossy red hue for vibrant and polished nails. With a quick-drying formula, it provides a salon-quality finish at home.",
    category: "beauty",
    price: 8.99,
    discountPercentage: 11.44,
    rating: 4.32,
    stock: 79,
    tags: ["beauty", "nail polish"],
    brand: "Nail Couture",
    sku: "BEA-NAI-NAI-005",
    weight: 8,
    dimensions: {
      width: 21.63,
      height: 16.48,
      depth: 29.84,
    },
    warrantyInformation: "1 month warranty",
    shippingInformation: "Ships overnight",
    availabilityStatus: "In Stock",
    reviews: [
      {
        rating: 2,
        comment: "Poor quality!",
        date: "2025-04-30T09:41:02.053Z",
        reviewerName: "Benjamin Wilson",
        reviewerEmail: "benjamin.wilson@x.dummyjson.com",
      },
      {
        rating: 5,
        comment: "Great product!",
        date: "2025-04-30T09:41:02.053Z",
        reviewerName: "Liam Smith",
        reviewerEmail: "liam.smith@x.dummyjson.com",
      },
      {
        rating: 1,
        comment: "Very unhappy with my purchase!",
        date: "2025-04-30T09:41:02.053Z",
        reviewerName: "Clara Berry",
        reviewerEmail: "clara.berry@x.dummyjson.com",
      },
    ],
    returnPolicy: "No return policy",
    minimumOrderQuantity: 22,
    meta: {
      createdAt: "2025-04-30T09:41:02.053Z",
      updatedAt: "2025-04-30T09:41:02.053Z",
      barcode: "4063010628104",
      qrCode: "https://cdn.dummyjson.com/public/qr-code.png",
    },
    images: [
      "https://cdn.dummyjson.com/product-images/beauty/red-nail-polish/1.webp",
    ],
    thumbnail:
      "https://cdn.dummyjson.com/product-images/beauty/red-nail-polish/thumbnail.webp",
  },
  {
    id: 6,
    title: "Updated ",
    description:
      "CK One by Calvin Klein is a classic unisex fragrance, known for its fresh and clean scent. It's a versatile fragrance suitable for everyday wear.",
    category: "fragrances",
    price: 149.99,
    discountPercentage: 1.89,
    rating: 4.7,
    stock: 29,
    tags: ["Rings", "perfumes"],
    brand: "Calvin Klein",
    sku: "FRA-CAL-CAL-006",
    weight: 7,
    dimensions: {
      width: 29.36,
      height: 27.76,
      depth: 20.72,
    },
    warrantyInformation: "1 week warranty",
    shippingInformation: "Ships overnight",
    availabilityStatus: "In Stock",
    reviews: [
      {
        rating: 2,
        comment: "Very disappointed!",
        date: "2025-04-30T09:41:02.053Z",
        reviewerName: "Layla Young",
        reviewerEmail: "layla.young@x.dummyjson.com",
      },
      {
        rating: 4,
        comment: "Fast shipping!",
        date: "2025-04-30T09:41:02.053Z",
        reviewerName: "Daniel Cook",
        reviewerEmail: "daniel.cook@x.dummyjson.com",
      },
      {
        rating: 3,
        comment: "Not as described!",
        date: "2025-04-30T09:41:02.053Z",
        reviewerName: "Jacob Cooper",
        reviewerEmail: "jacob.cooper@x.dummyjson.com",
      },
    ],
    returnPolicy: "90 days return policy",
    minimumOrderQuantity: 9,
    meta: {
      createdAt: "2025-04-30T09:41:02.053Z",
      updatedAt: "2025-04-30T09:41:02.053Z",
      barcode: "2451534060749",
      qrCode: "https://cdn.dummyjson.com/public/qr-code.png",
    },
    images: [
      "https://cdn.dummyjson.com/product-images/fragrances/calvin-klein-ck-one/1.webp",
      "https://cdn.dummyjson.com/product-images/fragrances/calvin-klein-ck-one/2.webp",
      "https://cdn.dummyjson.com/product-images/fragrances/calvin-klein-ck-one/3.webp",
    ],
    thumbnail:
      "https://cdn.dummyjson.com/product-images/fragrances/calvin-klein-ck-one/thumbnail.webp",
  },
  {
    id: 7,
    title: "Chanel Coco Noir Eau De",
    description:
      "Coco Noir by Chanel is an elegant and mysterious fragrance, featuring notes of grapefruit, rose, and sandalwood. Perfect for evening occasions.",
    category: "fragrances",
    price: 129.99,
    discountPercentage: 16.51,
    rating: 4.26,
    stock: 58,
    tags: ["fragrances", "perfumes"],
    brand: "Chanel",
    sku: "FRA-CHA-CHA-007",
    weight: 7,
    dimensions: {
      width: 24.5,
      height: 25.7,
      depth: 25.98,
    },
    warrantyInformation: "3 year warranty",
    shippingInformation: "Ships overnight",
    availabilityStatus: "In Stock",
    reviews: [
      {
        rating: 4,
        comment: "Highly impressed!",
        date: "2025-04-30T09:41:02.053Z",
        reviewerName: "Ruby Andrews",
        reviewerEmail: "ruby.andrews@x.dummyjson.com",
      },
      {
        rating: 5,
        comment: "Awesome product!",
        date: "2025-04-30T09:41:02.053Z",
        reviewerName: "Leah Henderson",
        reviewerEmail: "leah.henderson@x.dummyjson.com",
      },
      {
        rating: 5,
        comment: "Very happy with my purchase!",
        date: "2025-04-30T09:41:02.053Z",
        reviewerName: "Xavier Wright",
        reviewerEmail: "xavier.wright@x.dummyjson.com",
      },
    ],
    returnPolicy: "No return policy",
    minimumOrderQuantity: 1,
    meta: {
      createdAt: "2025-04-30T09:41:02.053Z",
      updatedAt: "2025-04-30T09:41:02.053Z",
      barcode: "4091737746820",
      qrCode: "https://cdn.dummyjson.com/public/qr-code.png",
    },
    images: [
      "https://cdn.dummyjson.com/product-images/fragrances/chanel-coco-noir-eau-de/1.webp",
      "https://cdn.dummyjson.com/product-images/fragrances/chanel-coco-noir-eau-de/2.webp",
      "https://cdn.dummyjson.com/product-images/fragrances/chanel-coco-noir-eau-de/3.webp",
    ],
    thumbnail:
      "https://cdn.dummyjson.com/product-images/fragrances/chanel-coco-noir-eau-de/thumbnail.webp",
  },
  {
    id: 8,
    title: "Dior J'adore",
    description:
      "J'adore by Dior is a luxurious and floral fragrance, known for its blend of ylang-ylang, rose, and jasmine. It embodies femininity and sophistication.",
    category: "fragrances",
    price: 89.99,
    discountPercentage: 14.72,
    rating: 3.8,
    stock: 98,
    tags: ["fragrances", "perfumes"],
    brand: "Dior",
    sku: "FRA-DIO-DIO-008",
    weight: 4,
    dimensions: {
      width: 27.67,
      height: 28.28,
      depth: 11.83,
    },
    warrantyInformation: "1 week warranty",
    shippingInformation: "Ships in 2 weeks",
    availabilityStatus: "In Stock",
    reviews: [
      {
        rating: 5,
        comment: "Great value for money!",
        date: "2025-04-30T09:41:02.053Z",
        reviewerName: "Nicholas Bailey",
        reviewerEmail: "nicholas.bailey@x.dummyjson.com",
      },
      {
        rating: 4,
        comment: "Great value for money!",
        date: "2025-04-30T09:41:02.053Z",
        reviewerName: "Penelope Harper",
        reviewerEmail: "penelope.harper@x.dummyjson.com",
      },
      {
        rating: 4,
        comment: "Great product!",
        date: "2025-04-30T09:41:02.053Z",
        reviewerName: "Emma Miller",
        reviewerEmail: "emma.miller@x.dummyjson.com",
      },
    ],
    returnPolicy: "7 days return policy",
    minimumOrderQuantity: 10,
    meta: {
      createdAt: "2025-04-30T09:41:02.053Z",
      updatedAt: "2025-04-30T09:41:02.053Z",
      barcode: "1445086097250",
      qrCode: "https://cdn.dummyjson.com/public/qr-code.png",
    },
    images: [
      "https://cdn.dummyjson.com/product-images/fragrances/dior-j'adore/1.webp",
      "https://cdn.dummyjson.com/product-images/fragrances/dior-j'adore/2.webp",
      "https://cdn.dummyjson.com/product-images/fragrances/dior-j'adore/3.webp",
    ],
    thumbnail:
      "https://cdn.dummyjson.com/product-images/fragrances/dior-j'adore/thumbnail.webp",
  },
  {
    id: 9,
    title: "Dolce Shine Eau de",
    description:
      "Dolce Shine by Dolce & Gabbana is a vibrant and fruity fragrance, featuring notes of mango, jasmine, and blonde woods. It's a joyful and youthful scent.",
    category: "fragrances",
    price: 69.99,
    discountPercentage: 0.62,
    rating: 3.96,
    stock: 4,
    tags: ["fragrances", "perfumes"],
    brand: "Dolce & Gabbana",
    sku: "FRA-DOL-DOL-009",
    weight: 6,
    dimensions: {
      width: 27.28,
      height: 29.88,
      depth: 18.3,
    },
    warrantyInformation: "3 year warranty",
    shippingInformation: "Ships in 1 month",
    availabilityStatus: "Low Stock",
    reviews: [
      {
        rating: 4,
        comment: "Would buy again!",
        date: "2025-04-30T09:41:02.053Z",
        reviewerName: "Mateo Bennett",
        reviewerEmail: "mateo.bennett@x.dummyjson.com",
      },
      {
        rating: 4,
        comment: "Highly recommended!",
        date: "2025-04-30T09:41:02.053Z",
        reviewerName: "Nolan Gonzalez",
        reviewerEmail: "nolan.gonzalez@x.dummyjson.com",
      },
      {
        rating: 5,
        comment: "Very happy with my purchase!",
        date: "2025-04-30T09:41:02.053Z",
        reviewerName: "Aurora Lawson",
        reviewerEmail: "aurora.lawson@x.dummyjson.com",
      },
    ],
    returnPolicy: "7 days return policy",
    minimumOrderQuantity: 2,
    meta: {
      createdAt: "2025-04-30T09:41:02.053Z",
      updatedAt: "2025-04-30T09:41:02.053Z",
      barcode: "3023868210708",
      qrCode: "https://cdn.dummyjson.com/public/qr-code.png",
    },
    images: [
      "https://cdn.dummyjson.com/product-images/fragrances/dolce-shine-eau-de/1.webp",
      "https://cdn.dummyjson.com/product-images/fragrances/dolce-shine-eau-de/2.webp",
      "https://cdn.dummyjson.com/product-images/fragrances/dolce-shine-eau-de/3.webp",
    ],
    thumbnail:
      "https://cdn.dummyjson.com/product-images/fragrances/dolce-shine-eau-de/thumbnail.webp",
  },
  {
    id: 10,
    title: "Gucci Bloom Eau de",
    description:
      "Gucci Bloom by Gucci is a floral and captivating fragrance, with notes of tuberose, jasmine, and Rangoon creeper. It's a modern and romantic scent.",
    category: "fragrances",
    price: 79.99,
    discountPercentage: 14.39,
    rating: 2.74,
    stock: 91,
    tags: ["fragrances", "perfumes"],
    brand: "Gucci",
    sku: "FRA-GUC-GUC-010",
    weight: 7,
    dimensions: {
      width: 20.92,
      height: 21.68,
      depth: 11.2,
    },
    warrantyInformation: "6 months warranty",
    shippingInformation: "Ships overnight",
    availabilityStatus: "In Stock",
    reviews: [
      {
        rating: 1,
        comment: "Very dissatisfied!",
        date: "2025-04-30T09:41:02.053Z",
        reviewerName: "Cameron Perez",
        reviewerEmail: "cameron.perez@x.dummyjson.com",
      },
      {
        rating: 5,
        comment: "Very happy with my purchase!",
        date: "2025-04-30T09:41:02.053Z",
        reviewerName: "Daniel Cook",
        reviewerEmail: "daniel.cook@x.dummyjson.com",
      },
      {
        rating: 4,
        comment: "Highly impressed!",
        date: "2025-04-30T09:41:02.053Z",
        reviewerName: "Addison Wright",
        reviewerEmail: "addison.wright@x.dummyjson.com",
      },
    ],
    returnPolicy: "No return policy",
    minimumOrderQuantity: 2,
    meta: {
      createdAt: "2025-04-30T09:41:02.053Z",
      updatedAt: "2025-04-30T09:41:02.053Z",
      barcode: "3170832177880",
      qrCode: "https://cdn.dummyjson.com/public/qr-code.png",
    },
    images: [
      "https://cdn.dummyjson.com/product-images/fragrances/gucci-bloom-eau-de/1.webp",
      "https://cdn.dummyjson.com/product-images/fragrances/gucci-bloom-eau-de/2.webp",
      "https://cdn.dummyjson.com/product-images/fragrances/gucci-bloom-eau-de/3.webp",
    ],
    thumbnail:
      "https://cdn.dummyjson.com/product-images/fragrances/gucci-bloom-eau-de/thumbnail.webp",
  },
  {
    id: 172,
    title: "Blue Women's Handbag",
    description:
      "The Blue Women's Handbag is a stylish and spacious accessory for everyday use. With a vibrant blue color and multiple compartments, it combines fashion and functionality.",
    category: "womens-bags",
    price: 49.99,
    discountPercentage: 17.88,
    rating: 2.92,
    stock: 76,
    tags: ["fashion accessories", "handbags"],
    brand: "Fashionista",
    sku: "WOM-FAS-BLU-172",
    weight: 7,
    dimensions: {
      width: 14.12,
      height: 11.89,
      depth: 25.69,
    },
    warrantyInformation: "1 year warranty",
    shippingInformation: "Ships in 1 week",
    availabilityStatus: "In Stock",
    reviews: [
      {
        rating: 3,
        comment: "Waste of money!",
        date: "2025-04-30T09:41:02.054Z",
        reviewerName: "Grace Perry",
        reviewerEmail: "grace.perry@x.dummyjson.com",
      },
      {
        rating: 3,
        comment: "Not worth the price!",
        date: "2025-04-30T09:41:02.054Z",
        reviewerName: "Evelyn Sanchez",
        reviewerEmail: "evelyn.sanchez@x.dummyjson.com",
      },
      {
        rating: 4,
        comment: "Highly impressed!",
        date: "2025-04-30T09:41:02.054Z",
        reviewerName: "Eli Ward",
        reviewerEmail: "eli.ward@x.dummyjson.com",
      },
    ],
    returnPolicy: "7 days return policy",
    minimumOrderQuantity: 5,
    meta: {
      createdAt: "2025-04-30T09:41:02.054Z",
      updatedAt: "2025-04-30T09:41:02.054Z",
      barcode: "0558998280008",
      qrCode: "https://cdn.dummyjson.com/public/qr-code.png",
    },
    images: [
      "https://cdn.dummyjson.com/product-images/womens-bags/blue-women's-handbag/1.webp",
      "https://cdn.dummyjson.com/product-images/womens-bags/blue-women's-handbag/2.webp",
      "https://cdn.dummyjson.com/product-images/womens-bags/blue-women's-handbag/3.webp",
    ],
    thumbnail:
      "https://cdn.dummyjson.com/product-images/womens-bags/blue-women's-handbag/thumbnail.webp",
  },
  {
    id: 173,
    title: "Heshe Women's Leather Bag",
    description:
      "The Heshe Women's Leather Bag is a luxurious and high-quality leather bag for the sophisticated woman. With a timeless design and durable craftsmanship, it's a versatile accessory.",
    category: "womens-bags",
    price: 129.99,
    discountPercentage: 3.87,
    rating: 4.92,
    stock: 99,
    tags: ["fashion accessories", "leather bags"],
    brand: "Heshe",
    sku: "WOM-HES-HES-173",
    weight: 3,
    dimensions: {
      width: 28.66,
      height: 20.56,
      depth: 6.62,
    },
    warrantyInformation: "5 year warranty",
    shippingInformation: "Ships overnight",
    availabilityStatus: "In Stock",
    reviews: [
      {
        rating: 5,
        comment: "Excellent quality!",
        date: "2025-04-30T09:41:02.054Z",
        reviewerName: "Hunter Gordon",
        reviewerEmail: "hunter.gordon@x.dummyjson.com",
      },
      {
        rating: 4,
        comment: "Awesome product!",
        date: "2025-04-30T09:41:02.054Z",
        reviewerName: "Mason Parker",
        reviewerEmail: "mason.parker@x.dummyjson.com",
      },
      {
        rating: 4,
        comment: "Awesome product!",
        date: "2025-04-30T09:41:02.054Z",
        reviewerName: "William Gonzalez",
        reviewerEmail: "william.gonzalez@x.dummyjson.com",
      },
    ],
    returnPolicy: "90 days return policy",
    minimumOrderQuantity: 5,
    meta: {
      createdAt: "2025-04-30T09:41:02.054Z",
      updatedAt: "2025-04-30T09:41:02.054Z",
      barcode: "4616258239513",
      qrCode: "https://cdn.dummyjson.com/public/qr-code.png",
    },
    images: [
      "https://cdn.dummyjson.com/product-images/womens-bags/heshe-women's-leather-bag/1.webp",
      "https://cdn.dummyjson.com/product-images/womens-bags/heshe-women's-leather-bag/2.webp",
      "https://cdn.dummyjson.com/product-images/womens-bags/heshe-women's-leather-bag/3.webp",
    ],
    thumbnail:
      "https://cdn.dummyjson.com/product-images/womens-bags/heshe-women's-leather-bag/thumbnail.webp",
  },
  {
    id: 174,
    title: "Prada Women Bag",
    description:
      "The Prada Women Bag is an iconic designer bag that exudes elegance and luxury. Crafted with precision and featuring the Prada logo, it's a statement piece for fashion enthusiasts.",
    category: "womens-bags",
    price: 599.99,
    discountPercentage: 14.09,
    rating: 2.71,
    stock: 75,
    tags: ["fashion accessories", "designer bags"],
    brand: "Prada",
    sku: "WOM-PRA-PRA-174",
    weight: 4,
    dimensions: {
      width: 21.84,
      height: 22.19,
      depth: 13.41,
    },
    warrantyInformation: "3 year warranty",
    shippingInformation: "Ships in 1-2 business days",
    availabilityStatus: "In Stock",
    reviews: [
      {
        rating: 2,
        comment: "Would not buy again!",
        date: "2025-04-30T09:41:02.054Z",
        reviewerName: "Caleb Perkins",
        reviewerEmail: "caleb.perkins@x.dummyjson.com",
      },
      {
        rating: 4,
        comment: "Great value for money!",
        date: "2025-04-30T09:41:02.054Z",
        reviewerName: "Carter Baker",
        reviewerEmail: "carter.baker@x.dummyjson.com",
      },
      {
        rating: 5,
        comment: "Highly recommended!",
        date: "2025-04-30T09:41:02.054Z",
        reviewerName: "Lucas Ramirez",
        reviewerEmail: "lucas.ramirez@x.dummyjson.com",
      },
    ],
    returnPolicy: "60 days return policy",
    minimumOrderQuantity: 1,
    meta: {
      createdAt: "2025-04-30T09:41:02.054Z",
      updatedAt: "2025-04-30T09:41:02.054Z",
      barcode: "9614237439330",
      qrCode: "https://cdn.dummyjson.com/public/qr-code.png",
    },
    images: [
      "https://cdn.dummyjson.com/product-images/womens-bags/prada-women-bag/1.webp",
      "https://cdn.dummyjson.com/product-images/womens-bags/prada-women-bag/2.webp",
      "https://cdn.dummyjson.com/product-images/womens-bags/prada-women-bag/3.webp",
    ],
    thumbnail:
      "https://cdn.dummyjson.com/product-images/womens-bags/prada-women-bag/thumbnail.webp",
  },
  {
    id: 175,
    title: "White Faux Leather Backpack",
    description:
      "The White Faux Leather Backpack is a trendy and practical backpack for the modern woman. With a sleek white design and ample storage space, it's perfect for both casual and on-the-go styles.",
    category: "womens-bags",
    price: 39.99,
    discountPercentage: 15.2,
    rating: 3.36,
    stock: 39,
    tags: ["fashion accessories", "backpacks"],
    brand: "Urban Chic",
    sku: "WOM-URB-WHI-175",
    weight: 7,
    dimensions: {
      width: 14.31,
      height: 23.29,
      depth: 28.91,
    },
    warrantyInformation: "2 year warranty",
    shippingInformation: "Ships in 1 week",
    availabilityStatus: "In Stock",
    reviews: [
      {
        rating: 4,
        comment: "Awesome product!",
        date: "2025-04-30T09:41:02.054Z",
        reviewerName: "Ava Harrison",
        reviewerEmail: "ava.harrison@x.dummyjson.com",
      },
      {
        rating: 1,
        comment: "Not as described!",
        date: "2025-04-30T09:41:02.054Z",
        reviewerName: "Liam Garcia",
        reviewerEmail: "liam.garcia@x.dummyjson.com",
      },
      {
        rating: 5,
        comment: "Great value for money!",
        date: "2025-04-30T09:41:02.054Z",
        reviewerName: "Cameron Perez",
        reviewerEmail: "cameron.perez@x.dummyjson.com",
      },
    ],
    returnPolicy: "90 days return policy",
    minimumOrderQuantity: 7,
    meta: {
      createdAt: "2025-04-30T09:41:02.054Z",
      updatedAt: "2025-04-30T09:41:02.054Z",
      barcode: "8983558170212",
      qrCode: "https://cdn.dummyjson.com/public/qr-code.png",
    },
    images: [
      "https://cdn.dummyjson.com/product-images/womens-bags/white-faux-leather-backpack/1.webp",
      "https://cdn.dummyjson.com/product-images/womens-bags/white-faux-leather-backpack/2.webp",
      "https://cdn.dummyjson.com/product-images/womens-bags/white-faux-leather-backpack/3.webp",
    ],
    thumbnail:
      "https://cdn.dummyjson.com/product-images/womens-bags/white-faux-leather-backpack/thumbnail.webp",
  },
  {
    id: 176,
    title: "Women Handbag Black",
    description:
      "The Women Handbag in Black is a classic and versatile accessory that complements various outfits. With a timeless black color and functional design, it's a must-have in every woman's wardrobe.",
    category: "womens-bags",
    price: 59.99,
    discountPercentage: 11.63,
    rating: 2.89,
    stock: 11,
    tags: ["fashion accessories", "handbags"],
    brand: "Elegance Collection",
    sku: "WOM-ELE-WOM-176",
    weight: 6,
    dimensions: {
      width: 29.76,
      height: 12.34,
      depth: 15.82,
    },
    warrantyInformation: "Lifetime warranty",
    shippingInformation: "Ships in 1 month",
    availabilityStatus: "In Stock",
    reviews: [
      {
        rating: 4,
        comment: "Very pleased!",
        date: "2025-04-30T09:41:02.054Z",
        reviewerName: "Natalie Price",
        reviewerEmail: "natalie.price@x.dummyjson.com",
      },
      {
        rating: 5,
        comment: "Great product!",
        date: "2025-04-30T09:41:02.054Z",
        reviewerName: "Emily Johnson",
        reviewerEmail: "emily.johnson@x.dummyjson.com",
      },
      {
        rating: 1,
        comment: "Waste of money!",
        date: "2025-04-30T09:41:02.054Z",
        reviewerName: "Henry Hill",
        reviewerEmail: "henry.hill@x.dummyjson.com",
      },
    ],
    returnPolicy: "60 days return policy",
    minimumOrderQuantity: 9,
    meta: {
      createdAt: "2025-04-30T09:41:02.054Z",
      updatedAt: "2025-04-30T09:41:02.054Z",
      barcode: "4283648448769",
      qrCode: "https://cdn.dummyjson.com/public/qr-code.png",
    },
    images: [
      "https://cdn.dummyjson.com/product-images/womens-bags/women-handbag-black/1.webp",
      "https://cdn.dummyjson.com/product-images/womens-bags/women-handbag-black/2.webp",
      "https://cdn.dummyjson.com/product-images/womens-bags/women-handbag-black/3.webp",
    ],
    thumbnail:
      "https://cdn.dummyjson.com/product-images/womens-bags/women-handbag-black/thumbnail.webp",
  },
  {
    id: 182,
    title: "Green Crystal Earring",
    description:
      "The Green Crystal Earring is a dazzling accessory that features a vibrant green crystal. With a classic design, it adds a touch of elegance to your ensemble, perfect for formal or special occasions.",
    category: "womens-jewellery",
    price: 29.99,
    discountPercentage: 15.24,
    rating: 3.96,
    stock: 54,
    tags: ["fashion accessories", "earrings"],
    sku: "WOM-BRD-GRE-182",
    weight: 2,
    dimensions: {
      width: 14.61,
      height: 22.92,
      depth: 12.52,
    },
    warrantyInformation: "5 year warranty",
    shippingInformation: "Ships in 3-5 business days",
    availabilityStatus: "In Stock",
    reviews: [
      {
        rating: 4,
        comment: "Would buy again!",
        date: "2025-04-30T09:41:02.054Z",
        reviewerName: "Michael Williams",
        reviewerEmail: "michael.williams@x.dummyjson.com",
      },
      {
        rating: 5,
        comment: "Great value for money!",
        date: "2025-04-30T09:41:02.054Z",
        reviewerName: "Samantha Howard",
        reviewerEmail: "samantha.howard@x.dummyjson.com",
      },
      {
        rating: 4,
        comment: "Excellent quality!",
        date: "2025-04-30T09:41:02.054Z",
        reviewerName: "Xavier Wright",
        reviewerEmail: "xavier.wright@x.dummyjson.com",
      },
    ],
    returnPolicy: "60 days return policy",
    minimumOrderQuantity: 15,
    meta: {
      createdAt: "2025-04-30T09:41:02.054Z",
      updatedAt: "2025-04-30T09:41:02.054Z",
      barcode: "1680580323411",
      qrCode: "https://cdn.dummyjson.com/public/qr-code.png",
    },
    images: [
      "https://cdn.dummyjson.com/product-images/womens-jewellery/green-crystal-earring/1.webp",
      "https://cdn.dummyjson.com/product-images/womens-jewellery/green-crystal-earring/2.webp",
      "https://cdn.dummyjson.com/product-images/womens-jewellery/green-crystal-earring/3.webp",
    ],
    thumbnail:
      "https://cdn.dummyjson.com/product-images/womens-jewellery/green-crystal-earring/thumbnail.webp",
  },
  {
    id: 183,
    title: "Green Oval Earring",
    description:
      "The Green Oval Earring is a stylish and versatile accessory with a unique oval shape. Whether for casual or dressy occasions, its green hue and contemporary design make it a standout piece.",
    category: "womens-jewellery",
    price: 24.99,
    discountPercentage: 15.18,
    rating: 3.57,
    stock: 73,
    tags: ["fashion accessories", "earrings"],
    sku: "WOM-BRD-GRE-183",
    weight: 10,
    dimensions: {
      width: 8.48,
      height: 6.24,
      depth: 5.72,
    },
    warrantyInformation: "3 months warranty",
    shippingInformation: "Ships in 3-5 business days",
    availabilityStatus: "In Stock",
    reviews: [
      {
        rating: 3,
        comment: "Would not buy again!",
        date: "2025-04-30T09:41:02.054Z",
        reviewerName: "Elena Long",
        reviewerEmail: "elena.long@x.dummyjson.com",
      },
      {
        rating: 5,
        comment: "Very satisfied!",
        date: "2025-04-30T09:41:02.054Z",
        reviewerName: "Layla Sullivan",
        reviewerEmail: "layla.sullivan@x.dummyjson.com",
      },
      {
        rating: 4,
        comment: "Would buy again!",
        date: "2025-04-30T09:41:02.054Z",
        reviewerName: "Xavier Wright",
        reviewerEmail: "xavier.wright@x.dummyjson.com",
      },
    ],
    returnPolicy: "60 days return policy",
    minimumOrderQuantity: 19,
    meta: {
      createdAt: "2025-04-30T09:41:02.054Z",
      updatedAt: "2025-04-30T09:41:02.054Z",
      barcode: "4782555577213",
      qrCode: "https://cdn.dummyjson.com/public/qr-code.png",
    },
    images: [
      "https://cdn.dummyjson.com/product-images/womens-jewellery/green-oval-earring/1.webp",
      "https://cdn.dummyjson.com/product-images/womens-jewellery/green-oval-earring/2.webp",
      "https://cdn.dummyjson.com/product-images/womens-jewellery/green-oval-earring/3.webp",
    ],
    thumbnail:
      "https://cdn.dummyjson.com/product-images/womens-jewellery/green-oval-earring/thumbnail.webp",
  },
  {
    id: 184,
    title: "Tropical Earring",
    description:
      "The Tropical Earring is a fun and playful accessory inspired by tropical elements. Featuring vibrant colors and a lively design, it's perfect for adding a touch of summer to your look.",
    category: "womens-jewellery",
    price: 19.99,
    discountPercentage: 0.76,
    rating: 4.4,
    stock: 1,
    tags: ["fashion accessories", "earrings"],
    sku: "WOM-BRD-TRO-184",
    weight: 3,
    dimensions: {
      width: 14.99,
      height: 15.76,
      depth: 16.09,
    },
    warrantyInformation: "3 year warranty",
    shippingInformation: "Ships in 1-2 business days",
    availabilityStatus: "Low Stock",
    reviews: [
      {
        rating: 5,
        comment: "Great product!",
        date: "2025-04-30T09:41:02.054Z",
        reviewerName: "Alexander Jones",
        reviewerEmail: "alexander.jones@x.dummyjson.com",
      },
      {
        rating: 4,
        comment: "Awesome product!",
        date: "2025-04-30T09:41:02.054Z",
        reviewerName: "Eli Ward",
        reviewerEmail: "eli.ward@x.dummyjson.com",
      },
      {
        rating: 1,
        comment: "Very unhappy with my purchase!",
        date: "2025-04-30T09:41:02.054Z",
        reviewerName: "Carter Rivera",
        reviewerEmail: "carter.rivera@x.dummyjson.com",
      },
    ],
    returnPolicy: "7 days return policy",
    minimumOrderQuantity: 31,
    meta: {
      createdAt: "2025-04-30T09:41:02.054Z",
      updatedAt: "2025-04-30T09:41:02.054Z",
      barcode: "7759380216135",
      qrCode: "https://cdn.dummyjson.com/public/qr-code.png",
    },
    images: [
      "https://cdn.dummyjson.com/product-images/womens-jewellery/tropical-earring/1.webp",
      "https://cdn.dummyjson.com/product-images/womens-jewellery/tropical-earring/2.webp",
      "https://cdn.dummyjson.com/product-images/womens-jewellery/tropical-earring/3.webp",
    ],
    thumbnail:
      "https://cdn.dummyjson.com/product-images/womens-jewellery/tropical-earring/thumbnail.webp",
  },
  {
    id: 177,
    title: "Black Women's Gown",
    description:
      "The Black Women's Gown is an elegant and timeless evening gown. With a sleek black design, it's perfect for formal events and special occasions, exuding sophistication and style.",
    category: "womens-dresses",
    price: 129.99,
    discountPercentage: 10.48,
    rating: 3.64,
    stock: 25,
    tags: ["clothing", "gowns"],
    sku: "WOM-BRD-BLA-177",
    weight: 2,
    dimensions: {
      width: 7.86,
      height: 9.02,
      depth: 25.82,
    },
    warrantyInformation: "Lifetime warranty",
    shippingInformation: "Ships in 1 week",
    availabilityStatus: "In Stock",
    reviews: [
      {
        rating: 4,
        comment: "Great value for money!",
        date: "2025-04-30T09:41:02.054Z",
        reviewerName: "Ethan Fletcher",
        reviewerEmail: "ethan.fletcher@x.dummyjson.com",
      },
      {
        rating: 3,
        comment: "Very dissatisfied!",
        date: "2025-04-30T09:41:02.054Z",
        reviewerName: "Julian Newton",
        reviewerEmail: "julian.newton@x.dummyjson.com",
      },
      {
        rating: 5,
        comment: "Very satisfied!",
        date: "2025-04-30T09:41:02.054Z",
        reviewerName: "Savannah Gomez",
        reviewerEmail: "savannah.gomez@x.dummyjson.com",
      },
    ],
    returnPolicy: "No return policy",
    minimumOrderQuantity: 5,
    meta: {
      createdAt: "2025-04-30T09:41:02.054Z",
      updatedAt: "2025-04-30T09:41:02.054Z",
      barcode: "0630346013554",
      qrCode: "https://cdn.dummyjson.com/public/qr-code.png",
    },
    images: [
      "https://cdn.dummyjson.com/product-images/womens-dresses/black-women's-gown/1.webp",
      "https://cdn.dummyjson.com/product-images/womens-dresses/black-women's-gown/2.webp",
      "https://cdn.dummyjson.com/product-images/womens-dresses/black-women's-gown/3.webp",
      "https://cdn.dummyjson.com/product-images/womens-dresses/black-women's-gown/4.webp",
    ],
    thumbnail:
      "https://cdn.dummyjson.com/product-images/womens-dresses/black-women's-gown/thumbnail.webp",
  },
  {
    id: 178,
    title: "Corset Leather With Skirt",
    description:
      "The Corset Leather With Skirt is a bold and edgy ensemble that combines a stylish corset with a matching skirt. Ideal for fashion-forward individuals, it makes a statement at any event.",
    category: "womens-dresses",
    price: 89.99,
    discountPercentage: 16.26,
    rating: 3.05,
    stock: 30,
    tags: ["clothing", "corsets", "skirts"],
    sku: "WOM-BRD-COR-178",
    weight: 1,
    dimensions: {
      width: 6.01,
      height: 12.6,
      depth: 11.62,
    },
    warrantyInformation: "2 year warranty",
    shippingInformation: "Ships overnight",
    availabilityStatus: "In Stock",
    reviews: [
      {
        rating: 5,
        comment: "Very happy with my purchase!",
        date: "2025-04-30T09:41:02.054Z",
        reviewerName: "Natalie Price",
        reviewerEmail: "natalie.price@x.dummyjson.com",
      },
      {
        rating: 4,
        comment: "Highly recommended!",
        date: "2025-04-30T09:41:02.054Z",
        reviewerName: "Sophia Jones",
        reviewerEmail: "sophia.jones@x.dummyjson.com",
      },
      {
        rating: 4,
        comment: "Highly recommended!",
        date: "2025-04-30T09:41:02.054Z",
        reviewerName: "Leo Rivera",
        reviewerEmail: "leo.rivera@x.dummyjson.com",
      },
    ],
    returnPolicy: "30 days return policy",
    minimumOrderQuantity: 3,
    meta: {
      createdAt: "2025-04-30T09:41:02.054Z",
      updatedAt: "2025-04-30T09:41:02.054Z",
      barcode: "2931500162745",
      qrCode: "https://cdn.dummyjson.com/public/qr-code.png",
    },
    images: [
      "https://cdn.dummyjson.com/product-images/womens-dresses/corset-leather-with-skirt/1.webp",
      "https://cdn.dummyjson.com/product-images/womens-dresses/corset-leather-with-skirt/2.webp",
      "https://cdn.dummyjson.com/product-images/womens-dresses/corset-leather-with-skirt/3.webp",
      "https://cdn.dummyjson.com/product-images/womens-dresses/corset-leather-with-skirt/4.webp",
    ],
    thumbnail:
      "https://cdn.dummyjson.com/product-images/womens-dresses/corset-leather-with-skirt/thumbnail.webp",
  },
  {
    id: 179,
    title: "Corset With Black Skirt",
    description:
      "The Corset With Black Skirt is a chic and versatile outfit that pairs a fashionable corset with a classic black skirt. It offers a trendy and coordinated look for various occasions.",
    category: "womens-dresses",
    price: 79.99,
    discountPercentage: 15.06,
    rating: 4.52,
    stock: 33,
    tags: ["clothing", "corsets", "skirts"],
    sku: "WOM-BRD-COR-179",
    weight: 7,
    dimensions: {
      width: 17.56,
      height: 28.42,
      depth: 23.95,
    },
    warrantyInformation: "1 month warranty",
    shippingInformation: "Ships in 1 week",
    availabilityStatus: "In Stock",
    reviews: [
      {
        rating: 5,
        comment: "Very satisfied!",
        date: "2025-04-30T09:41:02.054Z",
        reviewerName: "Lucas Allen",
        reviewerEmail: "lucas.allen@x.dummyjson.com",
      },
      {
        rating: 2,
        comment: "Disappointing product!",
        date: "2025-04-30T09:41:02.054Z",
        reviewerName: "Benjamin Wilson",
        reviewerEmail: "benjamin.wilson@x.dummyjson.com",
      },
      {
        rating: 5,
        comment: "Very happy with my purchase!",
        date: "2025-04-30T09:41:02.054Z",
        reviewerName: "Elena Long",
        reviewerEmail: "elena.long@x.dummyjson.com",
      },
    ],
    returnPolicy: "No return policy",
    minimumOrderQuantity: 5,
    meta: {
      createdAt: "2025-04-30T09:41:02.054Z",
      updatedAt: "2025-04-30T09:41:02.054Z",
      barcode: "9336695899390",
      qrCode: "https://cdn.dummyjson.com/public/qr-code.png",
    },
    images: [
      "https://cdn.dummyjson.com/product-images/womens-dresses/corset-with-black-skirt/1.webp",
      "https://cdn.dummyjson.com/product-images/womens-dresses/corset-with-black-skirt/2.webp",
      "https://cdn.dummyjson.com/product-images/womens-dresses/corset-with-black-skirt/3.webp",
      "https://cdn.dummyjson.com/product-images/womens-dresses/corset-with-black-skirt/4.webp",
    ],
    thumbnail:
      "https://cdn.dummyjson.com/product-images/womens-dresses/corset-with-black-skirt/thumbnail.webp",
  },
  {
    id: 180,
    title: "Dress Pea",
    description:
      "The Dress Pea is a stylish and comfortable dress with a pea pattern. Perfect for casual outings, it adds a playful and fun element to your wardrobe, making it a great choice for day-to-day wear.",
    category: "womens-dresses",
    price: 49.99,
    discountPercentage: 17.68,
    rating: 4.88,
    stock: 6,
    tags: ["clothing", "dresses"],
    sku: "WOM-BRD-DRE-180",
    weight: 1,
    dimensions: {
      width: 28.51,
      height: 20.99,
      depth: 12.58,
    },
    warrantyInformation: "2 year warranty",
    shippingInformation: "Ships overnight",
    availabilityStatus: "Low Stock",
    reviews: [
      {
        rating: 4,
        comment: "Fast shipping!",
        date: "2025-04-30T09:41:02.054Z",
        reviewerName: "Harper Turner",
        reviewerEmail: "harper.turner@x.dummyjson.com",
      },
      {
        rating: 1,
        comment: "Not worth the price!",
        date: "2025-04-30T09:41:02.054Z",
        reviewerName: "Luna Russell",
        reviewerEmail: "luna.russell@x.dummyjson.com",
      },
      {
        rating: 2,
        comment: "Would not buy again!",
        date: "2025-04-30T09:41:02.054Z",
        reviewerName: "Michael Johnson",
        reviewerEmail: "michael.johnson@x.dummyjson.com",
      },
    ],
    returnPolicy: "90 days return policy",
    minimumOrderQuantity: 6,
    meta: {
      createdAt: "2025-04-30T09:41:02.054Z",
      updatedAt: "2025-04-30T09:41:02.054Z",
      barcode: "8142375980193",
      qrCode: "https://cdn.dummyjson.com/public/qr-code.png",
    },
    images: [
      "https://cdn.dummyjson.com/product-images/womens-dresses/dress-pea/1.webp",
      "https://cdn.dummyjson.com/product-images/womens-dresses/dress-pea/2.webp",
      "https://cdn.dummyjson.com/product-images/womens-dresses/dress-pea/3.webp",
      "https://cdn.dummyjson.com/product-images/womens-dresses/dress-pea/4.webp",
    ],
    thumbnail:
      "https://cdn.dummyjson.com/product-images/womens-dresses/dress-pea/thumbnail.webp",
  },
  {
    id: 181,
    title: "Marni Red & Black Suit",
    description:
      "The Marni Red & Black Suit is a sophisticated and fashion-forward suit ensemble. With a combination of red and black tones, it showcases a modern design for a bold and confident look.",
    category: "womens-dresses",
    price: 179.99,
    discountPercentage: 19.02,
    rating: 4.48,
    stock: 62,
    tags: ["clothing", "suits"],
    sku: "WOM-BRD-MAR-181",
    weight: 3,
    dimensions: {
      width: 26.02,
      height: 9.93,
      depth: 25.48,
    },
    warrantyInformation: "5 year warranty",
    shippingInformation: "Ships in 2 weeks",
    availabilityStatus: "In Stock",
    reviews: [
      {
        rating: 5,
        comment: "Fast shipping!",
        date: "2025-04-30T09:41:02.054Z",
        reviewerName: "Avery Perez",
        reviewerEmail: "avery.perez@x.dummyjson.com",
      },
      {
        rating: 3,
        comment: "Very disappointed!",
        date: "2025-04-30T09:41:02.054Z",
        reviewerName: "Scarlett Wright",
        reviewerEmail: "scarlett.wright@x.dummyjson.com",
      },
      {
        rating: 4,
        comment: "Highly impressed!",
        date: "2025-04-30T09:41:02.054Z",
        reviewerName: "Claire Foster",
        reviewerEmail: "claire.foster@x.dummyjson.com",
      },
    ],
    returnPolicy: "90 days return policy",
    minimumOrderQuantity: 2,
    meta: {
      createdAt: "2025-04-30T09:41:02.054Z",
      updatedAt: "2025-04-30T09:41:02.054Z",
      barcode: "7479689140965",
      qrCode: "https://cdn.dummyjson.com/public/qr-code.png",
    },
    images: [
      "https://cdn.dummyjson.com/product-images/womens-dresses/marni-red-&-black-suit/1.webp",
      "https://cdn.dummyjson.com/product-images/womens-dresses/marni-red-&-black-suit/2.webp",
      "https://cdn.dummyjson.com/product-images/womens-dresses/marni-red-&-black-suit/3.webp",
      "https://cdn.dummyjson.com/product-images/womens-dresses/marni-red-&-black-suit/4.webp",
    ],
    thumbnail:
      "https://cdn.dummyjson.com/product-images/womens-dresses/marni-red-&-black-suit/thumbnail.webp",
  },
  {
    id: 190,
    title: "IWC Ingenieur Automatic Steel",
    description:
      "The IWC Ingenieur Automatic Steel watch is a durable and sophisticated timepiece. With a stainless steel case and automatic movement, it combines precision and style for watch enthusiasts.",
    category: "womens-watches",
    price: 4999.99,
    discountPercentage: 9.45,
    rating: 2.93,
    stock: 90,
    tags: ["watches", "luxury watches"],
    brand: "IWC",
    sku: "WOM-IWC-ING-190",
    weight: 3,
    dimensions: { width: 24.77, height: 24.66, depth: 6.09 },
    warrantyInformation: "1 year warranty",
    shippingInformation: "Ships overnight",
    availabilityStatus: "In Stock",
    reviews: [
      {
        rating: 3,
        comment: "Disappointing product!",
        date: "2025-04-30T09:41:02.054Z",
        reviewerName: "Gabriel Adams",
        reviewerEmail: "gabriel.adams@x.dummyjson.com",
      },
      {
        rating: 5,
        comment: "Great value for money!",
        date: "2025-04-30T09:41:02.054Z",
        reviewerName: "Evan Reed",
        reviewerEmail: "evan.reed@x.dummyjson.com",
      },
      {
        rating: 3,
        comment: "Would not buy again!",
        date: "2025-04-30T09:41:02.054Z",
        reviewerName: "Clara Berry",
        reviewerEmail: "clara.berry@x.dummyjson.com",
      },
    ],
    returnPolicy: "No return policy",
    minimumOrderQuantity: 1,
    meta: {
      createdAt: "2025-04-30T09:41:02.054Z",
      updatedAt: "2025-04-30T09:41:02.054Z",
      barcode: "7438522857639",
      qrCode: "https://cdn.dummyjson.com/public/qr-code.png",
    },
    images: [
      "https://cdn.dummyjson.com/product-images/womens-watches/iwc-ingenieur-automatic-steel/1.webp",
      "https://cdn.dummyjson.com/product-images/womens-watches/iwc-ingenieur-automatic-steel/2.webp",
      "https://cdn.dummyjson.com/product-images/womens-watches/iwc-ingenieur-automatic-steel/3.webp",
    ],
    thumbnail:
      "https://cdn.dummyjson.com/product-images/womens-watches/iwc-ingenieur-automatic-steel/thumbnail.webp",
  },
  {
    id: 191,
    title: "Rolex Cellini Moonphase",
    description:
      "The Rolex Cellini Moonphase watch is a masterpiece of horology. Featuring a moon phase complication, it showcases the craftsmanship and elegance that Rolex is renowned for.",
    category: "womens-watches",
    price: 15999.99,
    discountPercentage: 4.11,
    rating: 3.83,
    stock: 52,
    tags: ["watches", "luxury watches"],
    brand: "Rolex",
    sku: "WOM-ROL-ROL-191",
    weight: 10,
    dimensions: { width: 12.5, height: 20.63, depth: 25.04 },
    warrantyInformation: "1 month warranty",
    shippingInformation: "Ships in 1 week",
    availabilityStatus: "In Stock",
    reviews: [
      {
        rating: 4,
        comment: "Very happy with my purchase!",
        date: "2025-04-30T09:41:02.054Z",
        reviewerName: "Gabriel Hayes",
        reviewerEmail: "gabriel.hayes@x.dummyjson.com",
      },
      {
        rating: 5,
        comment: "Fast shipping!",
        date: "2025-04-30T09:41:02.054Z",
        reviewerName: "Logan Torres",
        reviewerEmail: "logan.torres@x.dummyjson.com",
      },
      {
        rating: 1,
        comment: "Disappointing product!",
        date: "2025-04-30T09:41:02.054Z",
        reviewerName: "Isabella Jackson",
        reviewerEmail: "isabella.jackson@x.dummyjson.com",
      },
    ],
    returnPolicy: "30 days return policy",
    minimumOrderQuantity: 1,
    meta: {
      createdAt: "2025-04-30T09:41:02.054Z",
      updatedAt: "2025-04-30T09:41:02.054Z",
      barcode: "4608359670564",
      qrCode: "https://cdn.dummyjson.com/public/qr-code.png",
    },
    images: [
      "https://cdn.dummyjson.com/product-images/womens-watches/rolex-cellini-moonphase/1.webp",
      "https://cdn.dummyjson.com/product-images/womens-watches/rolex-cellini-moonphase/2.webp",
      "https://cdn.dummyjson.com/product-images/womens-watches/rolex-cellini-moonphase/3.webp",
    ],
    thumbnail:
      "https://cdn.dummyjson.com/product-images/womens-watches/rolex-cellini-moonphase/thumbnail.webp",
  },
  {
    id: 192,
    title: "Rolex Datejust Women",
    description:
      "The Rolex Datejust Women's watch is an iconic timepiece designed for women. With a timeless design and a date complication, it offers both elegance and functionality.",
    category: "womens-watches",
    price: 10999.99,
    discountPercentage: 15.94,
    rating: 2.86,
    stock: 4,
    tags: ["watches", "luxury watches", "women's watches"],
    brand: "Rolex",
    sku: "WOM-ROL-ROL-192",
    weight: 3,
    dimensions: { width: 23.23, height: 7.19, depth: 28.95 },
    warrantyInformation: "5 year warranty",
    shippingInformation: "Ships in 2 weeks",
    availabilityStatus: "Low Stock",
    reviews: [
      {
        rating: 3,
        comment: "Not as described!",
        date: "2025-04-30T09:41:02.054Z",
        reviewerName: "Benjamin Wilson",
        reviewerEmail: "benjamin.wilson@x.dummyjson.com",
      },
      {
        rating: 5,
        comment: "Highly impressed!",
        date: "2025-04-30T09:41:02.054Z",
        reviewerName: "Madison Collins",
        reviewerEmail: "madison.collins@x.dummyjson.com",
      },
      {
        rating: 4,
        comment: "Very satisfied!",
        date: "2025-04-30T09:41:02.054Z",
        reviewerName: "Lucas Gray",
        reviewerEmail: "lucas.gray@x.dummyjson.com",
      },
    ],
    returnPolicy: "No return policy",
    minimumOrderQuantity: 1,
    meta: {
      createdAt: "2025-04-30T09:41:02.054Z",
      updatedAt: "2025-04-30T09:41:02.054Z",
      barcode: "1265605585958",
      qrCode: "https://cdn.dummyjson.com/public/qr-code.png",
    },
    images: [
      "https://cdn.dummyjson.com/product-images/womens-watches/rolex-datejust-women/1.webp",
      "https://cdn.dummyjson.com/product-images/womens-watches/rolex-datejust-women/2.webp",
      "https://cdn.dummyjson.com/product-images/womens-watches/rolex-datejust-women/3.webp",
    ],
    thumbnail:
      "https://cdn.dummyjson.com/product-images/womens-watches/rolex-datejust-women/thumbnail.webp",
  },
  {
    id: 193,
    title: "Watch Gold for Women",
    description:
      "The Gold Women's Watch is a stunning accessory that combines luxury and style. Featuring a gold-plated case and a chic design, it adds a touch of glamour to any outfit.",
    category: "womens-watches",
    price: 799.99,
    discountPercentage: 18.34,
    rating: 4.24,
    stock: 0,
    tags: ["watches", "women's watches"],
    brand: "Fashion Gold",
    sku: "WOM-FAS-WAT-193",
    weight: 1,
    dimensions: { width: 18.85, height: 28.59, depth: 7.21 },
    warrantyInformation: "2 year warranty",
    shippingInformation: "Ships in 1-2 business days",
    availabilityStatus: "Out of Stock",
    reviews: [
      {
        rating: 4,
        comment: "Highly impressed!",
        date: "2025-04-30T09:41:02.054Z",
        reviewerName: "Elena Baker",
        reviewerEmail: "elena.baker@x.dummyjson.com",
      },
      {
        rating: 4,
        comment: "Would buy again!",
        date: "2025-04-30T09:41:02.054Z",
        reviewerName: "Avery Barnes",
        reviewerEmail: "avery.barnes@x.dummyjson.com",
      },
      {
        rating: 5,
        comment: "Great product!",
        date: "2025-04-30T09:41:02.054Z",
        reviewerName: "Evelyn Sanchez",
        reviewerEmail: "evelyn.sanchez@x.dummyjson.com",
      },
    ],
    returnPolicy: "60 days return policy",
    minimumOrderQuantity: 1,
    meta: {
      createdAt: "2025-04-30T09:41:02.054Z",
      updatedAt: "2025-04-30T09:41:02.054Z",
      barcode: "8333241081413",
      qrCode: "https://cdn.dummyjson.com/public/qr-code.png",
    },
    images: [
      "https://cdn.dummyjson.com/product-images/womens-watches/watch-gold-for-women/1.webp",
      "https://cdn.dummyjson.com/product-images/womens-watches/watch-gold-for-women/2.webp",
      "https://cdn.dummyjson.com/product-images/womens-watches/watch-gold-for-women/3.webp",
    ],
    thumbnail:
      "https://cdn.dummyjson.com/product-images/womens-watches/watch-gold-for-women/thumbnail.webp",
  },
  {
    id: 194,
    title: "Women's Wrist Watch",
    description:
      "The Women's Wrist Watch is a versatile and fashionable timepiece for everyday wear. With a comfortable strap and a simple yet elegant design, it complements various styles.",
    category: "womens-watches",
    price: 129.99,
    discountPercentage: 12.6,
    rating: 3.52,
    stock: 12,
    tags: ["watches", "women's watches"],
    brand: "Fashion Co.",
    sku: "WOM-FAS-WOM-194",
    weight: 1,
    dimensions: { width: 26.1, height: 22.03, depth: 21.61 },
    warrantyInformation: "1 year warranty",
    shippingInformation: "Ships in 2 weeks",
    availabilityStatus: "In Stock",
    reviews: [
      {
        rating: 4,
        comment: "Very happy with my purchase!",
        date: "2025-04-30T09:41:02.054Z",
        reviewerName: "Harper Kelly",
        reviewerEmail: "harper.kelly@x.dummyjson.com",
      },
      {
        rating: 5,
        comment: "Highly recommended!",
        date: "2025-04-30T09:41:02.054Z",
        reviewerName: "Gabriel Bailey",
        reviewerEmail: "gabriel.bailey@x.dummyjson.com",
      },
      {
        rating: 5,
        comment: "Fast shipping!",
        date: "2025-04-30T09:41:02.054Z",
        reviewerName: "Natalie Price",
        reviewerEmail: "natalie.price@x.dummyjson.com",
      },
    ],
    returnPolicy: "No return policy",
    minimumOrderQuantity: 5,
    meta: {
      createdAt: "2025-04-30T09:41:02.054Z",
      updatedAt: "2025-04-30T09:41:02.054Z",
      barcode: "2093537854573",
      qrCode: "https://cdn.dummyjson.com/public/qr-code.png",
    },
    images: [
      "https://cdn.dummyjson.com/product-images/womens-watches/women's-wrist-watch/1.webp",
      "https://cdn.dummyjson.com/product-images/womens-watches/women's-wrist-watch/2.webp",
      "https://cdn.dummyjson.com/product-images/womens-watches/women's-wrist-watch/3.webp",
    ],
    thumbnail:
      "https://cdn.dummyjson.com/product-images/womens-watches/women's-wrist-watch/thumbnail.webp",
  },
];
  
  export default fashionJewellery;
  